#!/bin/bash
# Quick commands to view logs

echo "📋 Log Viewing Commands"
echo "======================="
echo ""
echo "1️⃣  View all logs (real-time):"
echo "   tail -f logs/application.log"
echo ""
echo "2️⃣  View errors only (real-time):"
echo "   tail -f logs/application-error.log"
echo ""
echo "3️⃣  View JSON logs (real-time, formatted):"
echo "   tail -f logs/application-json.log | jq ."
echo ""
echo "4️⃣  Search for specific request ID:"
echo "   grep 'REQUEST_ID_HERE' logs/application.log"
echo ""
echo "5️⃣  Count errors in last hour:"
echo "   grep 'ERROR' logs/application-error.log | grep \"\$(date +%Y-%m-%d\\ %H)\" | wc -l"
echo ""
echo "6️⃣  View last 50 lines:"
echo "   tail -50 logs/application.log"
echo ""
echo "7️⃣  Search for specific error:"
echo "   grep -i 'exception' logs/application-error.log"
echo ""
